spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

  datasource:
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_NAME:routine}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PWD:0319}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  jwt-secret: ${JWT_SECRET:dsadsasa}
  access-exp: ${JWT_ACCESS_EXP:180000000}
  jwt-header: ${JWT_HEADER:Authorization}
  jwt-prefix: ${JWT_PREFIX:Bearer}